fos_user:
    registration:
        confirmation:
            enabled: true
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: "%env(resolve:FOS_MAILER_USER)%"
        sender_name: "%env(resolve:FOS_MAILER_USER)%"